Street_Food/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("depart/list/",views.depart_list),
    path("create/",views.create),
    path("depart/add/",views.depart_add),
    path("depart/delete/",views.depart_delete),
    path("depart/<int:nid>/edit/",views.depart_edit),
    path("user/list/",views.user_list),
    path("user/add/",views.user_add),
    path("user/<int:nid>/delete/",views.user_delete),
    path("user/model/form/add/",views.user_model_form_add),
    path('user/<int:nid>/edit/',views.user_edit),
    path("pretty/list/",views.pretty_list),
    path("pretty/add/",views.pretty_add)
]

app01/models.py
from django.db import models
# python manage.py makemigrations
# python manage.py migrate
# Create your models here.
class Department(models.Model):
    title = models.CharField(verbose_name="部门标题",max_length=32)
    def __str__(self):
        return self.title

class UserInfo(models.Model):
    name = models.CharField(max_length=16)
    password = models.CharField(max_length=64)
    age = models.IntegerField()
    account = models.DecimalField(verbose_name="账户余额",max_digits=10,decimal_places=2,default=0)

    create_time = models.DateField(verbose_name="入职时间")

    depart = models.ForeignKey(to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL)
    gender_choices = (
        (1,"male"),
        (2,"female")
    )
    gender = models.SmallIntegerField(choices = gender_choices)

class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name="手机号",max_length=11)
    price = models.IntegerField(verbose_name="价格",default=0)
    level_choices = (
        (1,"1级"),
        (2,"2级"),
        (3,"3级"),
        (4,"4级")
    )

    level = models.SmallIntegerField(choices=level_choices,default=1)
    status_choices = (
        (1,"占用"),
        (2,"未占用")
    )
    status= models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=2)

app01/views.py
from django.shortcuts import render,HttpResponse,redirect
import requests

# Create your views here.
from app01 import models
from app01.models import Department,UserInfo,PrettyNum

def depart_list(request):
    queryset = Department.objects.all()
    return render(request,"depart_list.html",{"queryset":queryset})


def create(request):


    # Department.objects.create(title="销售部")
    # Department.objects.create(title="IT部")
    # UserInfo.objects.create(name="张伟",password="123",age=20,account=30.15,create_time="2022-1-1",depart_id=1,gender=1)
    # UserInfo.objects.create(name="王明",password="456",age=30,account=40.3,create_time="2023-1-1",depart_id=2,gender=1)
    # UserInfo.objects.create(name="李爱",password="789",age=26,account=37,create_time="2024-1-1",depart_id=4,gender=2)
    PrettyNum.objects.create(mobile="12345678912",price=1000,level=1,status=1)
    PrettyNum.objects.create(mobile="12345678913", price=2000, level=2, status=2)
    PrettyNum.objects.create(mobile="12345678914", price=3000, level=3, status=1)


    return HttpResponse("添加成功")

def depart_add(request):
    """ 添加部门 """
    if request.method == "GET":
        return render(request, 'depart_add.html')

    # 获取用户POST提交过来的数据（title输入为空）
    title = request.POST.get("title")

    # 保存到数据库
    Department.objects.create(title=title)

    # 重定向回部门列表
    return redirect("/depart/list/")

def depart_delete(request):
    nid = request.GET.get("nid")
    Department.objects.filter(id = nid).delete()

    return redirect("/depart/list/")

def depart_edit(request,nid):
    if request.method == "GET":
        row_object = Department.objects.filter(id = nid).first()

        return render(request,"depart_edit.html",{"row_object":row_object})

    title = request.POST.get("title")
    Department.objects.filter(id = nid).update(title = title)
    return redirect("/depart/list/")


def user_list(request):
    queryset = UserInfo.objects.all()

    return render(request,"user_list.html",{"queryset":queryset})

def user_add(request):
    if request.method == "GET":
        context={
            "gender_choices" : UserInfo.gender_choices,
            "depart_list" : Department.objects.all()
        }
        return render(request,"user_add.html",context)
    name = request.POST.get("user")
    pwd = request.POST.get("pwd")
    age = request.POST.get("age")
    ac = request.POST.get("ac")
    ctime = request.POST.get("ctime")
    gd = request.POST.get("gd")
    dp = request.POST.get("dp")

    UserInfo.objects.create(name=name,password=pwd,age=age,account=ac,create_time=ctime,depart_id=dp,gender=gd)
    return redirect("/user/list/")

from django import forms

class UserModelForm(forms.ModelForm):
    name = forms.CharField(min_length=2,label="用户名")
    class Meta:
        model = UserInfo #所要添加的models里的类
        fields = ["name","password","age","account","create_time","gender","depart"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # 给每一个输入框的字段，添加class="form-control"
        for name,field in self.fields.items():
            if name == "password":
                continue
            field.widget.attrs = {"class":"form-control","placeholder":field.label}


def user_model_form_add(request):
    if request.method == "GET": #用户打开提交用户的页面时，通过get方法
        form = UserModelForm()
        return render(request,"user_model_form_add.html",{"form":form})

    # 当用户通过POST提交数据，需要对数据校验
    form = UserModelForm(data=request.POST) #生成对象时，继承之前用户填的数据
    if form.is_valid():
        form.save()
        return redirect("/user/list/")

    # 如果校验失败，显示错误信息，再次加载网页
    return render(request,"user_model_form_add.html",{"form":form})

def user_edit(request,nid):
    # 根据ID去获取要编辑的那一行数据对象，
    row_object = UserInfo.objects.filter(id=nid).first()

    # 并把该对象添加到form里，作为编辑的默认值
    if request.method == "GET":
        form = UserModelForm(instance=row_object)
        return render(request,'user_edit.html',{'form':form})

    form = UserModelForm(data=request.POST,instance=row_object)
    if form.is_valid():

        # form.instance.password = "987"
        # 在用户手动添加的以外的地方进行提交
        form.save()
        return redirect('/user/list/')
    return render(request,'user_edit.html',{'form':form})

def user_delete(request,nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')

def pretty_list(request):
    queryset = PrettyNum.objects.all()

    return render(request,"pretty_num.html",{"queryset":queryset})

class PrettyNumForm(forms.ModelForm):
    class Meta:
        model = PrettyNum #所要添加的models里的类
        # fields = ["mobile","price","level","status"]
        fields = "__all__"
        # exclude = ['level']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # 给每一个输入框的字段，添加class="form-control"
        for name,field in self.fields.items():
            # if name == "price":
            #     continue
            field.widget.attrs = {"class":"form-control","placeholder":field.label}

def pretty_add(request):
    if request.method == "GET": #用户打开提交用户的页面时，通过get方法
        form = PrettyNumForm()
        return render(request,"pretty_add.html",{"form":form})

    # 当用户通过POST提交数据，需要对数据校验
    form = PrettyNumForm(data=request.POST) #生成对象时，继承之前用户填的数据
    if form.is_valid():
        form.save()
        return redirect("/pretty/list/")

    # 如果校验失败，显示错误信息，再次加载网页
    return render(request,"pretty_add.html",{"form":form})



app01/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建部门 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    {#所有涉及post请求(即需要获取用户输入的东西时)都需要加入此句#}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="title"/>
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 修改部门 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        {#title表示用户新输入的值，属于post方法，通过 title = request.POST.get("title")获取                        #}
                        <input type="text" class="form-control" placeholder="标题" name="title"
                               value="{{ row_object.title }}"/>
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建部门
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部门列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ obj.id }}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app01/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> 联通用户管理系统 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="#">Link</a></li>


            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">登录</a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">武沛齐 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

app01/templates/pretty_add.html
{% extends 'layout.html' %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建号码 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app01/templates/pretty_num.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/pretty/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建号码
            </a>

{#            <a class="btn btn-success" href="/user/model/form/add/">#}
{#                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>#}
{#                新建用户ModelForm#}
{#            </a>#}
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                号码列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Mobile</th>
                    <th>Price</th>
                    <th>Level</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="#">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建用户 </h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label>姓名</label>
                        <input type="text" class="form-control" placeholder="姓名" name="user" />
                    </div>

                    <div class="form-group">
                        <label>密码</label>
                        <input type="text" class="form-control" placeholder="密码" name="pwd"/>
                    </div>

                    <div class="form-group">
                        <label>年龄</label>
                        <input type="text" class="form-control" placeholder="年龄" name="age"/>
                    </div>

                    <div class="form-group">
                        <label>余额</label>
                        <input type="text" class="form-control" placeholder="余额" name="ac"/>
                    </div>


                    <div class="form-group">
                        <label>入职时间</label>
                        <input type="text" class="form-control" placeholder="入职时间" name="ctime"/>
                    </div>

                    <div class="form-group">
                        <label>性别</label>
                        <select class="form-control" name="gd">
                            {% for item in gender_choices %}
                                <option value="{{ item.0 }}">{{ item.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label>部门</label>
                        <select class="form-control" name="dp">
                            {% for item in depart_list %}
                                <option value="{{ item.id }}">{{ item.title }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/user_edit.html
{% extends 'layout.html' %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 编辑用户 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app01/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

            <a class="btn btn-success" href="/user/model/form/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户ModelForm
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app01/templates/user_model_form_add.html
{% extends 'layout.html' %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建用户 </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}